services:
  fastapi:
    build: .
    ports:
      - 8000:8000
    networks:
      - app_network

  streamlit:
    build: ./streamlit_app
    ports:
      - 8501:8501
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge